name: Format

on:
    push:
     branches: [ ts ]
     paths:
      - ts/**

permissions:
  contents: write

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Prettier
        run: npm install prettier
      - name: Run Prettiers
        run: npx prettier --tab-width 4 --print-width 100 --trailing-comma es5  --ignore-path "$(CURDIR)/node_modules/*" --write ts/
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically applying Prettier changes
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          branch: ${{ github.head_ref }}
      # - name: Run JSON Prettier
      #   run: npx prettier --write "ts/**/*.json" --no-error-on-unmatched-pattern
      # - name: Commit JSON Prettier cchanges
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Format json via prettier
      #     commit_user_name: GitHub Actions
      #     commit_user_email: actions@github.com
      #     commit_author: GitHub Actions <actions@github.com>
      #     branch: ${{ github.head_ref }}
