name: Release Wasm

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            wasm:
              - 'JS/wasm/**'
    # start of the build job
      - name: Build Javy Core
        working-directory: .
        run: |
          make add all
      - name: Build CLI
        working-directory: .
        run: |
          make build-arakoo
      - name: Build Jsonnet
        working-directory: .
        run: |
          make build-jsonnet
    # start of the release job
      - name: Create out directory
        working-directory: .
        run: |
          mkdir bin/
    
      - name: Copy arakoo bin
        working-directory: .
        run: |
          cp target/release/arakoo bin/
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip Jsonnet
        working-directory: .
        run: |
          # remove node_modules
          rm -rf JS/jsonnet/node_modules
          zip -qq jsonnet.zip -d JS/jsonnet/

      - name: Copy jsonnet bin
        working-directory: .
        run: |
          cp -r jsonnet.zip bin/

      - name: Copy Javy bin
        working-directory: .
        run: |
          cp target/release/javy bin/

      - name: Upload Release Binary
        uses: actions/upload-artifact@v2
        with:
          name: arakoo-${{ env.RELEASE_TAG }}-x86_64
          path: bin

  release:
    name: release-wasm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: arakoo-${{ env.RELEASE_TAG }}-x86_64
          path: Output
      - name: Display structure of downloaded files
        run: ls -R

      - name: Get variables
        id: vars
        run: echo "tag_name=${{ env.RELEASE_TAG }}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./Output/*

          tag_name: ${{ env.RELEASE_TAG }}
